name: Run quality checks

on:
  push:
    branches:
      - master
      - '*.x'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set PHP version
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          coverage: none

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install composer dependencies
        run: composer install --quiet --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Run phpcs
        run: composer phpcs

      - name: Run phpstan
        run: composer phpstan
